### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by danik4985** [travisbrown/memory.lol#13]
you dont mind that the tool you created can be and most likely will be used for doxxing people? that seems ok (or even good) to you?

**Comment by travisbrown** [comment]
To take a specific example: I used to do a lot of open source work in the Scala programming language community, which has a serious problem with abuse and harassment. One specific abusive account that was actively involved in Scala conversations on Twitter for years was [`@0___9____01`](https://twitter.com/0___9____01) (among other obscure screen names). Here are a few examples of tweets from the account:

* [16 January 2021](http://web.archive.org/web/20210117051102/https://twitter.com/0___9____01/status/1350671895964782593): the joke is that men now think its acceptable for their wife or even gf to deny it from you. it should always be on your terms, thats its how it always has been.
* [16 January 2021](http://web.archive.org/web/20210117051102/https://twitter.com/0___9____01/status/1350671895964782593): spousal "rape" lmao. they really have taken everything from you dont they?
* [22 December 2020](http://web.archive.org/web/20201222144912/https://twitter.com/0___9____01/status/1341303475838222336): There are multiple reasons why men would become trans. The endproduct is usually tied to them. They basically boil down to those are "passing" with the right light and makeup, and there's the one that wear a dress, a wig and call it a day.
* [15 July 2020](http://web.archive.org/web/20200716052614/https://twitter.com/0___9____01/status/1283597549350289416): that's what happens when you throw Jews into the "white" definition. They fire you and then force you to apologize for your behavior.
* [7 June 2020](http://web.archive.org/web/20200608034125/https://twitter.com/0___9____01/status/1269784723506827269): How did hitler came to power genius? How did the anti jewish narrative came about? These are simple questions that anyone that isn't brain dead like you will know the answer
* [25 February 2019](https://twitter.com/caraesten/status/1100161590458896384) (screenshot): imagine being so privileged that you can have people refer to you as a woman by just putting a dress and make up. thats what I call privilege!

Using this index I was able to find that the account was operated by a person named Iratxo Flores-Lorca, who was also active in the community under his real name, attending conferences, [winning a prize](https://archive.today/2021.11.08-205802/https://www.signifytechnology.com/blog/2017/10/scale-by-the-bay-competition-winner-announced), etc. After his name was revealed, he apparently lost his job, the recruiting company that awarded the prize removed all public mention of it, and he has deleted his GitHub account.

Lorca wasn't doxxed. Nobody published his address or other private information. His abusive anonymous account was de-anonymized, and yes, that seems like a good thing to me.

That's just one use case for the tool. Another is to support research into hate speech or harassment on a larger scale. For example it's been used to take a list of known screen names involved in movements like Gamergate, QAnon, Stop the Steal, etc., and to find other screen names for those accounts, which can then be used to scrape content from the Wayback Machine for analysis. That also is not doxxing, and is also in my view a good thing.

Of course the index could also be used to cause harm. For the month that the service was public we were monitoring how it was used, and were allowing anyone to request removal of their former screen names. In the past week I've become convinced that that wasn't enough, and that the full index probably shouldn't be publicly available (and [it's not](https://github.com/travisbrown/memory.lol#current-access-restrictions)), but it will continue to be available to a trusted group of activists and researchers.

Hope that answers your question!

**Comment by danik4985** [comment]
Thanks for the answer. Just two quick questions:

1. What do you think is the difference between doxxing and "de-annonymizing" someone who clearly wants to be annonymized?

2. When you say "research of hate speech" what exactly do you mean? Like how do you research it?

P.S. since you're talking about still providing this to journalists, have you ever heard of Taylor Lorenz? 😉
